"""empty message

Revision ID: 42304af7c543
Revises: b446012de83d
Create Date: 2023-04-01 10:37:35.750101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42304af7c543'
down_revision = 'b446012de83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fav_name', sa.String(length=120), nullable=False),
    sa.Column('fav_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fav_id'),
    sa.UniqueConstraint('fav_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
