"""empty message

Revision ID: 5f025c1a289f
Revises: 42304af7c543
Create Date: 2023-04-01 18:47:13.669683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f025c1a289f'
down_revision = '42304af7c543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_fav_id_key', type_='unique')
        batch_op.drop_column('fav_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('favorites_fav_id_key', ['fav_id'])

    # ### end Alembic commands ###
