"""empty message

Revision ID: 6f590215abd8
Revises: 5f025c1a289f
Create Date: 2023-04-01 19:24:04.307854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f590215abd8'
down_revision = '5f025c1a289f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['fav_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('fav_id')

    # ### end Alembic commands ###
